pipeline {
    agent any

    environment {
        NODE_ENV = 'staging'
        SSH_HOST = 'ubuntu@ 98.89.132.2'
        SSH_KEY_ID = 'baoafrik-key'
        APP_DIR = 'backend'
        APP_NAME = 'baoafrik'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'fonsah-staging',
                    url: 'git@github.com/Bao-Technologies-and-Travels/BaoAfrik.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir("${env.APP_DIR}") {
                    sh 'mv .env.example .env'
                    sh 'npm ci'
                }
            }
        }

        stage('Test') {
            steps {
                dir("${env.APP_DIR}") {
                    echo 'Running tests...'
                    sh 'npm test'
                }
            }
        }

        stage('Build') {
            steps {
                dir("${env.APP_DIR}") {
                    echo 'Building the API...'
                    sh 'npm start'
                }
            }
        }

        stage('Deploy') {
            steps {
                sshagent([env.SSH_KEY_ID]) {
                    sh """
                    ssh -o StrictHostKeyChecking=no ${env.SSH_HOST} '
                        cd ~/backend &&
                        git pull origin fonsah-staging &&
                        npm ci --production &&
                        npm run build &&
                        pm2 stop ${env.APP_NAME} || true &&
                        pm2 start dist/server.js --name ${env.APP_NAME}
                    '
                    """
                }
            }
        }

        stage('Email Notification') {
            mail(
                bcc: '',
                body: "${env.JOB_NAME} - Build # ${env.BUILD_NUMBER} - ${currentBuild.currentResult}: Check console output at ${env.BUILD_URL} to view the results. This is an auto-generated email. Do not reply.",
                cc: '',
                from: '',
                replyTo: '',
                subject: "${env.JOB_NAME} - Build # ${env.BUILD_NUMBER} - ${currentBuild.currentResult}!",
                to: 'ashprincepageo@gmail.com'
            )
        }
    }
}
