// Country phone codes with ISO country codes and flags
// Based on ISO 3166-1 alpha-2 codes
export interface CountryPhoneCode {
  name: string;
  code: string; // ISO country code (2 letters, lowercase)
  dialCode: string; // Phone dialing code (e.g., '+1', '+44')
  flag: string; // ISO country code for flag
}

export const countryPhoneCodes: CountryPhoneCode[] = [
  { name: 'United States', code: 'us', dialCode: '+1', flag: 'us' },
  { name: 'United Kingdom', code: 'gb', dialCode: '+44', flag: 'gb' },
  { name: 'Canada', code: 'ca', dialCode: '+1', flag: 'ca' },
  { name: 'Australia', code: 'au', dialCode: '+61', flag: 'au' },
  { name: 'Germany', code: 'de', dialCode: '+49', flag: 'de' },
  { name: 'France', code: 'fr', dialCode: '+33', flag: 'fr' },
  { name: 'Italy', code: 'it', dialCode: '+39', flag: 'it' },
  { name: 'Spain', code: 'es', dialCode: '+34', flag: 'es' },
  { name: 'Netherlands', code: 'nl', dialCode: '+31', flag: 'nl' },
  { name: 'Belgium', code: 'be', dialCode: '+32', flag: 'be' },
  { name: 'Switzerland', code: 'ch', dialCode: '+41', flag: 'ch' },
  { name: 'Austria', code: 'at', dialCode: '+43', flag: 'at' },
  { name: 'Sweden', code: 'se', dialCode: '+46', flag: 'se' },
  { name: 'Norway', code: 'no', dialCode: '+47', flag: 'no' },
  { name: 'Denmark', code: 'dk', dialCode: '+45', flag: 'dk' },
  { name: 'Finland', code: 'fi', dialCode: '+358', flag: 'fi' },
  { name: 'Poland', code: 'pl', dialCode: '+48', flag: 'pl' },
  { name: 'Portugal', code: 'pt', dialCode: '+351', flag: 'pt' },
  { name: 'Greece', code: 'gr', dialCode: '+30', flag: 'gr' },
  { name: 'Ireland', code: 'ie', dialCode: '+353', flag: 'ie' },
  { name: 'Japan', code: 'jp', dialCode: '+81', flag: 'jp' },
  { name: 'China', code: 'cn', dialCode: '+86', flag: 'cn' },
  { name: 'India', code: 'in', dialCode: '+91', flag: 'in' },
  { name: 'South Korea', code: 'kr', dialCode: '+82', flag: 'kr' },
  { name: 'Singapore', code: 'sg', dialCode: '+65', flag: 'sg' },
  { name: 'Malaysia', code: 'my', dialCode: '+60', flag: 'my' },
  { name: 'Thailand', code: 'th', dialCode: '+66', flag: 'th' },
  { name: 'Indonesia', code: 'id', dialCode: '+62', flag: 'id' },
  { name: 'Philippines', code: 'ph', dialCode: '+63', flag: 'ph' },
  { name: 'Vietnam', code: 'vn', dialCode: '+84', flag: 'vn' },
  { name: 'Brazil', code: 'br', dialCode: '+55', flag: 'br' },
  { name: 'Mexico', code: 'mx', dialCode: '+52', flag: 'mx' },
  { name: 'Argentina', code: 'ar', dialCode: '+54', flag: 'ar' },
  { name: 'Chile', code: 'cl', dialCode: '+56', flag: 'cl' },
  { name: 'Colombia', code: 'co', dialCode: '+57', flag: 'co' },
  { name: 'Peru', code: 'pe', dialCode: '+51', flag: 'pe' },
  { name: 'Venezuela', code: 've', dialCode: '+58', flag: 've' },
  { name: 'Egypt', code: 'eg', dialCode: '+20', flag: 'eg' },
  { name: 'South Africa', code: 'za', dialCode: '+27', flag: 'za' },
  { name: 'Nigeria', code: 'ng', dialCode: '+234', flag: 'ng' },
  { name: 'Kenya', code: 'ke', dialCode: '+254', flag: 'ke' },
  { name: 'Ghana', code: 'gh', dialCode: '+233', flag: 'gh' },
  { name: 'Ethiopia', code: 'et', dialCode: '+251', flag: 'et' },
  { name: 'Tanzania', code: 'tz', dialCode: '+255', flag: 'tz' },
  { name: 'Uganda', code: 'ug', dialCode: '+256', flag: 'ug' },
  { name: 'Algeria', code: 'dz', dialCode: '+213', flag: 'dz' },
  { name: 'Morocco', code: 'ma', dialCode: '+212', flag: 'ma' },
  { name: 'Tunisia', code: 'tn', dialCode: '+216', flag: 'tn' },
  { name: 'Libya', code: 'ly', dialCode: '+218', flag: 'ly' },
  { name: 'Sudan', code: 'sd', dialCode: '+249', flag: 'sd' },
  { name: 'Angola', code: 'ao', dialCode: '+244', flag: 'ao' },
  { name: 'Mozambique', code: 'mz', dialCode: '+258', flag: 'mz' },
  { name: 'Cameroon', code: 'cm', dialCode: '+237', flag: 'cm' },
  { name: 'Ivory Coast', code: 'ci', dialCode: '+225', flag: 'ci' },
  { name: 'Madagascar', code: 'mg', dialCode: '+261', flag: 'mg' },
  { name: 'Burkina Faso', code: 'bf', dialCode: '+226', flag: 'bf' },
  { name: 'Mali', code: 'ml', dialCode: '+223', flag: 'ml' },
  { name: 'Malawi', code: 'mw', dialCode: '+265', flag: 'mw' },
  { name: 'Zambia', code: 'zm', dialCode: '+260', flag: 'zm' },
  { name: 'Zimbabwe', code: 'zw', dialCode: '+263', flag: 'zw' },
  { name: 'Senegal', code: 'sn', dialCode: '+221', flag: 'sn' },
  { name: 'Chad', code: 'td', dialCode: '+235', flag: 'td' },
  { name: 'Guinea', code: 'gn', dialCode: '+224', flag: 'gn' },
  { name: 'Rwanda', code: 'rw', dialCode: '+250', flag: 'rw' },
  { name: 'Benin', code: 'bj', dialCode: '+229', flag: 'bj' },
  { name: 'Burundi', code: 'bi', dialCode: '+257', flag: 'bi' },
  { name: 'Togo', code: 'tg', dialCode: '+228', flag: 'tg' },
  { name: 'Sierra Leone', code: 'sl', dialCode: '+232', flag: 'sl' },
  { name: 'Libya', code: 'ly', dialCode: '+218', flag: 'ly' },
  { name: 'Central African Republic', code: 'cf', dialCode: '+236', flag: 'cf' },
  { name: 'Niger', code: 'ne', dialCode: '+227', flag: 'ne' },
  { name: 'Mauritania', code: 'mr', dialCode: '+222', flag: 'mr' },
  { name: 'Eritrea', code: 'er', dialCode: '+291', flag: 'er' },
  { name: 'Gambia', code: 'gm', dialCode: '+220', flag: 'gm' },
  { name: 'Botswana', code: 'bw', dialCode: '+267', flag: 'bw' },
  { name: 'Namibia', code: 'na', dialCode: '+264', flag: 'na' },
  { name: 'Gabon', code: 'ga', dialCode: '+241', flag: 'ga' },
  { name: 'Lesotho', code: 'ls', dialCode: '+266', flag: 'ls' },
  { name: 'Guinea-Bissau', code: 'gw', dialCode: '+245', flag: 'gw' },
  { name: 'Equatorial Guinea', code: 'gq', dialCode: '+240', flag: 'gq' },
  { name: 'Mauritius', code: 'mu', dialCode: '+230', flag: 'mu' },
  { name: 'Eswatini', code: 'sz', dialCode: '+268', flag: 'sz' },
  { name: 'Djibouti', code: 'dj', dialCode: '+253', flag: 'dj' },
  { name: 'Comoros', code: 'km', dialCode: '+269', flag: 'km' },
  { name: 'Cape Verde', code: 'cv', dialCode: '+238', flag: 'cv' },
  { name: 'Sao Tome and Principe', code: 'st', dialCode: '+239', flag: 'st' },
  { name: 'Seychelles', code: 'sc', dialCode: '+248', flag: 'sc' },
  { name: 'Russia', code: 'ru', dialCode: '+7', flag: 'ru' },
  { name: 'Turkey', code: 'tr', dialCode: '+90', flag: 'tr' },
  { name: 'Saudi Arabia', code: 'sa', dialCode: '+966', flag: 'sa' },
  { name: 'United Arab Emirates', code: 'ae', dialCode: '+971', flag: 'ae' },
  { name: 'Israel', code: 'il', dialCode: '+972', flag: 'il' },
  { name: 'Iran', code: 'ir', dialCode: '+98', flag: 'ir' },
  { name: 'Iraq', code: 'iq', dialCode: '+964', flag: 'iq' },
  { name: 'Pakistan', code: 'pk', dialCode: '+92', flag: 'pk' },
  { name: 'Bangladesh', code: 'bd', dialCode: '+880', flag: 'bd' },
  { name: 'Afghanistan', code: 'af', dialCode: '+93', flag: 'af' },
  { name: 'Sri Lanka', code: 'lk', dialCode: '+94', flag: 'lk' },
  { name: 'Nepal', code: 'np', dialCode: '+977', flag: 'np' },
  { name: 'Myanmar', code: 'mm', dialCode: '+95', flag: 'mm' },
  { name: 'Cambodia', code: 'kh', dialCode: '+855', flag: 'kh' },
  { name: 'Laos', code: 'la', dialCode: '+856', flag: 'la' },
  { name: 'Mongolia', code: 'mn', dialCode: '+976', flag: 'mn' },
  { name: 'North Korea', code: 'kp', dialCode: '+850', flag: 'kp' },
  { name: 'Taiwan', code: 'tw', dialCode: '+886', flag: 'tw' },
  { name: 'Hong Kong', code: 'hk', dialCode: '+852', flag: 'hk' },
  { name: 'Macau', code: 'mo', dialCode: '+853', flag: 'mo' },
  { name: 'New Zealand', code: 'nz', dialCode: '+64', flag: 'nz' },
  { name: 'Fiji', code: 'fj', dialCode: '+679', flag: 'fj' },
  { name: 'Papua New Guinea', code: 'pg', dialCode: '+675', flag: 'pg' },
  { name: 'Chile', code: 'cl', dialCode: '+56', flag: 'cl' },
  { name: 'Uruguay', code: 'uy', dialCode: '+598', flag: 'uy' },
  { name: 'Paraguay', code: 'py', dialCode: '+595', flag: 'py' },
  { name: 'Bolivia', code: 'bo', dialCode: '+591', flag: 'bo' },
  { name: 'Ecuador', code: 'ec', dialCode: '+593', flag: 'ec' },
  { name: 'Guyana', code: 'gy', dialCode: '+592', flag: 'gy' },
  { name: 'Suriname', code: 'sr', dialCode: '+597', flag: 'sr' },
  { name: 'French Guiana', code: 'gf', dialCode: '+594', flag: 'gf' },
  { name: 'Belize', code: 'bz', dialCode: '+501', flag: 'bz' },
  { name: 'Costa Rica', code: 'cr', dialCode: '+506', flag: 'cr' },
  { name: 'El Salvador', code: 'sv', dialCode: '+503', flag: 'sv' },
  { name: 'Guatemala', code: 'gt', dialCode: '+502', flag: 'gt' },
  { name: 'Honduras', code: 'hn', dialCode: '+504', flag: 'hn' },
  { name: 'Nicaragua', code: 'ni', dialCode: '+505', flag: 'ni' },
  { name: 'Panama', code: 'pa', dialCode: '+507', flag: 'pa' },
  { name: 'Cuba', code: 'cu', dialCode: '+53', flag: 'cu' },
  { name: 'Jamaica', code: 'jm', dialCode: '+1', flag: 'jm' },
  { name: 'Haiti', code: 'ht', dialCode: '+509', flag: 'ht' },
  { name: 'Dominican Republic', code: 'do', dialCode: '+1', flag: 'do' },
  { name: 'Trinidad and Tobago', code: 'tt', dialCode: '+1', flag: 'tt' },
  { name: 'Barbados', code: 'bb', dialCode: '+1', flag: 'bb' },
  { name: 'Bahamas', code: 'bs', dialCode: '+1', flag: 'bs' },
  { name: 'Belarus', code: 'by', dialCode: '+375', flag: 'by' },
  { name: 'Ukraine', code: 'ua', dialCode: '+380', flag: 'ua' },
  { name: 'Kazakhstan', code: 'kz', dialCode: '+7', flag: 'kz' },
  { name: 'Uzbekistan', code: 'uz', dialCode: '+998', flag: 'uz' },
  { name: 'Azerbaijan', code: 'az', dialCode: '+994', flag: 'az' },
  { name: 'Armenia', code: 'am', dialCode: '+374', flag: 'am' },
  { name: 'Georgia', code: 'ge', dialCode: '+995', flag: 'ge' },
  { name: 'Moldova', code: 'md', dialCode: '+373', flag: 'md' },
  { name: 'Latvia', code: 'lv', dialCode: '+371', flag: 'lv' },
  { name: 'Lithuania', code: 'lt', dialCode: '+370', flag: 'lt' },
  { name: 'Estonia', code: 'ee', dialCode: '+372', flag: 'ee' },
  { name: 'Czech Republic', code: 'cz', dialCode: '+420', flag: 'cz' },
  { name: 'Slovakia', code: 'sk', dialCode: '+421', flag: 'sk' },
  { name: 'Slovenia', code: 'si', dialCode: '+386', flag: 'si' },
  { name: 'Croatia', code: 'hr', dialCode: '+385', flag: 'hr' },
  { name: 'Bosnia and Herzegovina', code: 'ba', dialCode: '+387', flag: 'ba' },
  { name: 'Serbia', code: 'rs', dialCode: '+381', flag: 'rs' },
  { name: 'Montenegro', code: 'me', dialCode: '+382', flag: 'me' },
  { name: 'North Macedonia', code: 'mk', dialCode: '+389', flag: 'mk' },
  { name: 'Albania', code: 'al', dialCode: '+355', flag: 'al' },
  { name: 'Bulgaria', code: 'bg', dialCode: '+359', flag: 'bg' },
  { name: 'Romania', code: 'ro', dialCode: '+40', flag: 'ro' },
  { name: 'Hungary', code: 'hu', dialCode: '+36', flag: 'hu' },
  { name: 'Iceland', code: 'is', dialCode: '+354', flag: 'is' },
  { name: 'Luxembourg', code: 'lu', dialCode: '+352', flag: 'lu' },
  { name: 'Malta', code: 'mt', dialCode: '+356', flag: 'mt' },
  { name: 'Cyprus', code: 'cy', dialCode: '+357', flag: 'cy' },
  { name: 'Lebanon', code: 'lb', dialCode: '+961', flag: 'lb' },
  { name: 'Jordan', code: 'jo', dialCode: '+962', flag: 'jo' },
  { name: 'Syria', code: 'sy', dialCode: '+963', flag: 'sy' },
  { name: 'Yemen', code: 'ye', dialCode: '+967', flag: 'ye' },
  { name: 'Oman', code: 'om', dialCode: '+968', flag: 'om' },
  { name: 'Qatar', code: 'qa', dialCode: '+974', flag: 'qa' },
  { name: 'Bahrain', code: 'bh', dialCode: '+973', flag: 'bh' },
  { name: 'Kuwait', code: 'kw', dialCode: '+965', flag: 'kw' },
  { name: 'Kyrgyzstan', code: 'kg', dialCode: '+996', flag: 'kg' },
  { name: 'Tajikistan', code: 'tj', dialCode: '+992', flag: 'tj' },
  { name: 'Turkmenistan', code: 'tm', dialCode: '+993', flag: 'tm' },
  { name: 'Congo', code: 'cg', dialCode: '+242', flag: 'cg' },
  { name: 'Democratic Republic of the Congo', code: 'cd', dialCode: '+243', flag: 'cd' },
  { name: 'Liberia', code: 'lr', dialCode: '+231', flag: 'lr' },
  { name: 'South Sudan', code: 'ss', dialCode: '+211', flag: 'ss' },
];

// Sort by country name for easier searching
export const sortedCountryPhoneCodes = [...countryPhoneCodes].sort((a, b) => 
  a.name.localeCompare(b.name)
);
